Set Operations is useful for comparing two Numpy arrays. SO to find intersection, union and difference between arrays
For rank 1 arrays:<br>
`np.intersect1d(x,y))` **They all return numpy arrays**<br>
`np.setdiff1d(x,y))`<br>
`np.union1d(x,y))`<br>
When sort is used as a function so np.sort(), it doesnt change the original array <br>
But when it is used as a method the original array is changed. ndarry.sort()<br><br>
**For sorting, axis=0 actually sorts by column and axis=1 sorts by row**

In [1]:
import numpy as np

In [3]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print(x[x > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
print(x[x <= 7])

[0 1 2 3 4 5 6 7]


In [15]:
x[(x > 10) & (x < 17)] = -1
print(x)

[1 2 3 4 5 6 7]


In [25]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([4,3,2,9,9,8])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 3 4]
[1 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [30]:
print(np.sort(np.unique(y)))
#print(np.sort(y))
print("Original array doesnt change: ", y)

[2 3 4 8 9]
Original array doesnt change:  [4 3 2 9 9 8]


In [33]:
x = np.random.randint(1, 11, size=(10))
print(x)
#x.sort()
x.sort()
print("The original array is changed:", x)

[ 6 10 10  4  3  9  6  4  9  9]
The original array is changed: [ 3  4  4  6  6  9  9  9 10 10]


In [39]:
x = np.random.randint(1, 11, size=(4, 5))
print(x)

[[ 3 10  4  3  2]
 [ 1 10  1  8  8]
 [ 1  5  3  1  4]
 [ 2  9  2  7  5]]


In [42]:
#sort by row
print(np.sort(x, axis=0))

[[ 1  5  1  1  2]
 [ 1  9  2  3  4]
 [ 2 10  3  7  5]
 [ 3 10  4  8  8]]


In [41]:
#sort by column
print(np.sort(x, axis=1))

[[ 2  3  3  4 10]
 [ 1  1  8  8 10]
 [ 1  1  3  4  5]
 [ 2  2  5  7  9]]
