Generally there are 3 ways of slicing:<br>
ndarry[start:end] *start is inclusive end is exclusive*<br>
ndarry[start:] *start is inclusive*<br>
ndarry[:end] *end is exclusive*<br>
When you slice an array the variable youre assigning it to is not a new array rather its a window into the old one. So changes in new array will be reflected in the new one. **Use the `np.copy` function instead**<br>
`no.copy(ndarray)` or `ndarry.copy()` is used to create a new numpy array<br>

In [2]:
import numpy as np

In [3]:
#(4,5) 4 rows 5 columns
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
#first 1:4 is 1-3 rows and then 2:5 is 2-4 columns
#below is the same as
z = x[1:, 2:]
print(z, "\n")
z = x[1:4, 2:5]
print(z, '\n')
z = x[[1,3], 1:]
print(z, '\n')
z = x[[1,2,3]]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]] 

[[ 8  9 10]
 [13 14 15]
 [18 19 20]] 

[[ 7  8  9 10]
 [17 18 19 20]] 

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [9]:
#rank 1
z = x[:, 2] #Grab everything on third row
print(z)

[ 3  8 13 18]


In [11]:
#rank 2
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [17]:
z[3,0] = 255
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17 255  19  20]]


In [18]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
z = np.copy(x[1:, 2:])    #Can also do x[1:,2:].copy()
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [21]:
z[2,2] = 555
print(z)
print("\n", x)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
indices = np.array([1,3])
z = x[indices, :]
print(z)
print()
y = x[:, indices]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [26]:
print(np.diag(x))

[ 0  6 12 18]


In [29]:
print(np.diag(x, k=1))   #By default k = 0 which points to the main diagonal. k=1 prints 1 step above diagonal
print(np.diag(x, k=-1)) #-1 prints 1 step below diagonal 

[ 1  7 13 19]
[ 5 11 17]


In [30]:
#extract unique elements in rank n numpy array
x = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(np.unique(x))

[1 2 3 4 5 6]
