Numpy allows for element-wise operations and also matrix operations.<br>
This is for **element-wise operations**<br>
Broadcasting: term used to describe how numpy handles element wise arithmetic operations with arrays of different shapes<br>
Since we are doing element wise operations, the arrays being operated on must have the same shape or be broadcastable<br>


In [31]:
import numpy as np

In [32]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x, y)

[1 2 3 4] [5 6 7 8]


In [33]:
print(x + y)
print(np.add(x, y))   #This gives you to access to options you can tweak

[ 6  8 10 12]
[ 6  8 10 12]


In [34]:
print(x - y)
print(np.subtract(x, y))   #This gives you to access to options you can tweak
print(x * y)
print(np.multiply(x, y))   #This gives you to access to options you can tweak
print(x / y)
print(np.divide(x, y))   #This gives you to access to options you can tweak

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [35]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [36]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [37]:
print(x + y)
print()
print(x - y)
print()
print(x * y)
print()
print(x / y)

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [38]:
x = np.array([1,2,3,4])
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [39]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [40]:
print(np.power(x, 2))

[ 1  4  9 16]


In [41]:
x = np.arange(1, 5).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [42]:
print(x.mean())

2.5


In [43]:
print("Mean of column: ", x.mean(axis=0, dtype=int))
print()
print("Mean of rows: ", x.mean(axis=1))

Mean of column:  [2 3]

Mean of rows:  [1.5 3.5]


In [44]:
print("Sum of all ", x.sum())
print("Sum of columns ", x.sum(axis=0))
print("Sum of rows ", x.sum(axis=1))

Sum of all  10
Sum of columns  [4 6]
Sum of rows  [3 7]


In [45]:
x.std()

1.118033988749895

In [46]:
np.median(x)

2.5

In [47]:
x.max()

4

In [48]:
x.min()

1

In [49]:
print(x)

[[1 2]
 [3 4]]


In [50]:
print(3 + x)   #same as print(x + 3)

[[4 5]
 [6 7]]


In [52]:
print(x - 3)

[[-2 -1]
 [ 0  1]]


In [53]:
x = np.arange(3)
print(x)

[0 1 2]


In [55]:
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
print(x + y)  #This adds 0 to all rows in first column and 1 to 2nd column and 2 to 3rd column

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [58]:
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [61]:
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
print(x + y)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [64]:
#TO have a column of 1 and next of 2s and so on
x = np.zeros((4,4), dtype=int)
print(x)
y = np.array([1,2,3,4])
print(y)
print()
print(x + y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1 2 3 4]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
