**This is creating numpy arrays using normal python list**<br>
**Functions to use are:**<br>
    `x = np.array([1,2,3,4,5])` create a rank 1 array<br>
    `x.shape` tuple of sizes of each dimension <br>
    `x.size` size of entire array<br>
    `x.dtype` dataype of elements in the array


In [26]:
import numpy as np

#Creating numpy arrays using normal python list
x = np.array([1, 2, 3, 4, 5])

In [27]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [28]:
#dtype returns the data type of elements in the array
x.dtype

dtype('int64')

In [29]:
x.shape

(5,)

In [30]:
#Two dimensional array from nested python list
Y = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
Y.shape #colum x row

(4, 3)

In [32]:
Y.size #column * row

12

In [33]:
x = np.array(['Hello', 'World'])
print(x)
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

['Hello' 'World']
shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [34]:
#This will convert the ints to strings because numpy arrays elements cant mix data types
x = np.array([1,2,'Hello', 'World'])
print(x)
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

['1' '2' 'Hello' 'World']
shape:  (4,)
type:  <class 'numpy.ndarray'>
dtype:  <U21


In [35]:
#upcasting: upcasts integers in array to floats to avoid losing precision in numerical computations
x = np.array([1,2.5,4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [36]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x, "dtype: {}".format(x.dtype))

[1 2 3] dtype: int64


In [37]:
#we can save data into a file with extension npy for later use like below
x = np.array([1,2,3,4,5])
np.save('my_array', x)

In [38]:
#you can load saved data like this:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
