`y = np.delete(x, 0, axis=0)` this code deletes from a rank 2 array.<br>
**#axis 0 = row and axis 1 = column**<br>
`x = np.append(x, [7,8,9])` *this is used to append values to a rank 1 array*
`x = np.append(x, 1)` *to append only one value to a rank 1 array*<br><br>
`y = np.append(x, [[10,11,12]], axis=0)` to append a row of 10, 11, 12 to a rank 2 array<br>
`z = np.append(x, [[10],[11],[12]], axis=1)` to append a column to a rank 2 array<br>
`x = np.insert(x, 2, [3,4])` insert at position 2 values 3 and 4<br>
`y = np.insert(x, 1, [4,5,6], axis=0)` insert into row 1 values 4, 5, 6<br>
`y = np.insert(x, 1, [[5],[6]], axis=1)` insert 5 and 6 in each column of the rows<br><br><br>
Numpy allows stacking of Numpy arrays on eachother of side by side.<br>
*Vstack* vertical stacking<br>
*Hstack* horizontal stacking **Yyou need to reshape before doing hstack**<br>

In [33]:
import numpy as np

In [34]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [35]:
print("1st element: {}".format(x[0]))
print("3rd element: {}".format(x[2]))
print("5th element: {}".format(x[4]))

1st element: 1
3rd element: 3
5th element: 5


In [36]:
print("1st element: {}".format(x[-5]))
print("3rd element: {}".format(x[-3]))
print("5th element: {}".format(x[-1]))

1st element: 1
3rd element: 3
5th element: 5


In [37]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [38]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print("This is 1x1: {}".format(x[0,0]))
print("This is 1x3: {}".format(x[1,2]))
print("This is 3x1: {}".format(x[2,1]))

This is 1x1: 1
This is 1x3: 6
This is 3x1: 8


In [40]:
x[0,0] = 11
x[1,2] = 12
x[2,1] = 22
print(x)

[[11  2  3]
 [ 4  5 12]
 [ 7 22  9]]


In [41]:
x = np.array([1,2,3,4,5])
print(x)

#delete index 0 and 4
x = np.delete(x, [0,4])
print(x)

#delete only index 1
x = np.delete(x, 1)
print(x)

[1 2 3 4 5]
[2 3 4]
[2 4]


In [42]:
x = np.arange(1,10).reshape(3,3)
print(x)

#axis 0 = row and axis 1 = column
y = np.delete(x, 0, axis=0)
print('\n',y)
y = np.delete(x, 0, axis=1)
print('\n',y)
y = np.delete(x, [0,2], axis=1)
print('\n',y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2 3]
 [5 6]
 [8 9]]

 [[2]
 [5]
 [8]]


In [46]:
x = np.array([1,2,3,4,5])
print(x)
x = np.append(x, 6)
x = np.append(x, [7,8,9])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]


In [49]:
x = np.arange(1,10).reshape(3,3)
print(x)
y = np.append(x, [[10,11,12]], axis=0)
print(y)
z = np.append(x, [[10],[11],[12]], axis=1)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [50]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [51]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [52]:
x = np.array([[1,2,3],[7,8,9]])
print(x)

[[1 2 3]
 [7 8 9]]


In [53]:
y = np.insert(x, 1, [4,5,6], axis=0)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
y = np.insert(x, 1, 4, axis=1)
print(y)
y = np.insert(x, 1, [[5],[6]], axis=1)
print("\n", y)

[[1 4 2 3]
 [7 4 8 9]]

 [[1 5 6 2 3]
 [7 5 6 8 9]]


In [63]:
x = np.array([1,2])
print(x)
print()
y = np.array([[3,4], [5,6]])
print(y)

[1 2]

[[3 4]
 [5 6]]


In [68]:
z = np.vstack((x, y))
print(z)
print()
a = np.hstack((y, x.reshape(2,1)))
print(a)

[[1 2]
 [3 4]
 [5 6]]

[[3 4 1]
 [5 6 2]]
