**This is creating numpy arrays using built in Functions**<br>
`np.zeros((3,4))` create 3x4 matrix default dtype = float with values 0<br>
`np.ones((3,3))` create 3x3 matrix default dtype= float with values 1<br>
`np.full((4,3), 5)` creates 4x3 matrix with default that corresponds to the value you pass and dtype=type of value<br>
`np.eye(4)` make identity matrix <br>
`np.diag([10,20,30,40])` does the same as eye but with your own values<br>
`np.arange(start, stop, step)` this goes from start (inclusive) to stop (exclusive) and steps<br>
`np.linspace(start, stop, n)` this gives n numbers from start to stop (both inclusive) evenly spaced. Requires at least 2 numbers: start and stop<br>. *Can set it to excluvie by including , endpoint=false*<br>
`np.reshape(x, (4,4))` reshape an np array to a matrix<br>
`np.random.random(3,3)` creates a 3x3 matrix before 0 (inclusive) and 1 (exclusive). module.function<br>
`np.random.randint(4, 15, (3,2))` creates a 3x2 matrix with values between 4 (inclusive) and 15 (exclusive)<br>

In [1]:
import numpy as np

In [4]:
#By default this creates a 3x4 matrix with dtype=float64.
X = np.zeros((3,4), dtype=int)
print(X)
print(X.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [5]:
X = np.ones((4,4))
print(X)
print(X.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [12]:
#Default of this corresponds to what you put in either int or float or String
X = np.full((4,3), 5)
#X = np.full((4,3),5, dtype=float)

print(X)
print(X.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
int64


In [15]:
X= np.eye(5, dtype=int)
print(X)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [17]:
X = np.diag([10,20,30,40])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [18]:
X = np.arange(1,10,2)
print(X)

[1 3 5 7 9]


In [21]:
x = np.linspace(0, 25, 10)
y = np.linspace(0, 25, 10, endpoint=False)
print(x)
print()
print(y)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [24]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [27]:
#Some functions can be applied as methods
x = np.arange(20).reshape((10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [32]:
x = np.linspace(0, 50, 10, endpoint=False).reshape((5,2))
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [34]:
#THis prints a number between 0 (inclusive) and 1 (exclusive)
#first random is the module second one is the function within the random module
x = np.random.random((3,3))
print(x)

[[0.3444202  0.40864767 0.55922489]
 [0.76487321 0.29005227 0.18870531]
 [0.78939978 0.54744118 0.3985113 ]]


In [36]:
x = np.random.randint(4, 15, (3,2))
print(x)

[[12  5]
 [ 8  6]
 [11  7]]


In [37]:
#create a normal distribution with mean = 0, standard deviation = 0.1 and dimensions = 1000x1000
x = np.random.normal(0, 0.1, size=(1000, 1000))
print(x)

[[-1.04412016e-01 -1.30404149e-01  1.10394807e-02 ...  1.72334077e-01
   1.19148275e-01  1.50259743e-02]
 [-3.60057012e-02 -7.93238554e-03  1.32611237e-01 ... -1.24742459e-03
   9.00169692e-02  1.34420155e-01]
 [-6.52279564e-02 -1.61994254e-01 -6.75296437e-02 ... -2.23191758e-01
  -8.08190712e-02  7.64078355e-02]
 ...
 [-6.98748294e-02  6.60847456e-02 -3.16580213e-02 ...  2.49135277e-02
   2.23685230e-02 -9.12538167e-02]
 [-2.19490346e-01  9.01909023e-02 -1.36646900e-01 ...  1.17073796e-01
   8.18810178e-02 -1.36660099e-01]
 [ 1.26053240e-01 -2.03449150e-04  3.05963404e-02 ... -1.25425342e-01
   6.71783523e-03 -1.52028597e-01]]


In [38]:
print('mean: ',x.mean())
print('std: ',x.std())
print('max: ',x.max())
print('min: ',x.min())
print('# positive: ',(x > 0).sum())
print('# negative: ',(x < 0).sum())

mean:  7.263850601837861e-06
std:  0.10010632230509804
max:  0.48238192390748424
min:  -0.45426089682254844
# positive:  500279
# negative:  499721


In [42]:
#Test 1: Print a 4 x 4 rank n array from 2 - 32exclusive consecutive even numbers
x = np.arange(2, 33, 2).reshape((4,4))
print(x)
print("With linspace")
x = np.linspace(2, 32, 16).reshape(4,4)
print(x)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
With linspace
[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]
